templates:
# Антитеррор
  - id: "antiterror"
    enabled: true
    name: "Антитеррор"
    subject: "Обязательное прохождение курса и тестирования по антитеррористической безопасности"
    body_template: "/opt/invite-mailer/templates/antiterror.html"
    mode: "once"
    validity_days: null

    departments:
      include:
        - "*"
      exclude: []

# Антикоррупция
  - id: "anticorruption"
    enabled: true
    name: "Антикоррупция"
    subject: "Обязательное прохождение тренинга и тестирования по антикоррупционной безопасности"
    body_template: "/opt/invite-mailer/templates/anticorruption.html"
    mode: "once"
    validity_days: null
    audience:
      type: "explicit_list"