templates:
# Антитеррор
  - id: "antiterror"
    enabled: true
    name: "Антитеррор"
    subject: "Обязательное прохождение курса и тестирования по антитеррористической безопасности"
    body_template: "/opt/invite-mailer/templates/antiterror.html"
    mode: "once"
    validity_days: null

    departments:
      include:
        - "*"
      exclude: []